### PR TITLE
Add conditional loading (browser/node versions of serialization-lib)

### PR DESCRIPTION
**Pull request by klntsky**
Partially addresses #69.

Nix builds are still TODO.

Note that other PRs should change `serialization-lib` imports when this is merged (by copy-pasting import code from here)

### CODE REVIEW

**Review by MatthewCroughan — APPROVED** [review]

**Comment by nixinator** [comment]
Having to to commit the nodepackages.nix , it's bit and ugly, but no way around it at this time.

**Review by ngua — CHANGES_REQUESTED** [review]
I'm having a build error from `purs-loader` when trying to build with webpack. I'll take a look tomorrow to figure out what the issue could be

**Review by ngua — CHANGES_REQUESTED** [review]
I got everything working despite webpack's immensely confusing error messages:

- It looks like you haven't merged with your newest deserialization branch? At any rate, I merged that PR already so if you merge with master it should be OK
- Of course we need to adjust the CSL import in the `Deserialization.UnspentOutput` FFI module
- We also need to add `convertInput` to `Deserialization.UnspentOutput`'s exports
- And the comment below about `npm run dev`

**Comment by klntsky** [comment]
I made some more changes to ensure websocket wrapper works in the browser.

@ngua what was the problem with purs-loader?

**Comment by ngua** [comment]
@klntsky The `purs-loader` thing was a misleading error from webpack. The issue was just that the PS wasn't compiling. I didn't have the time that evening to investigate further and found the real issue the next day

**Review by ngua — APPROVED** [review]

**Pull request merged**
